// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: bag_item.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addItem = `-- name: AddItem :one
INSERT INTO Bag_item (Bag_id, Item_id, Amount)
VALUES ($1, $2, $3)
RETURNING bag_id, item_id, amount
`

type AddItemParams struct {
	BagID  uuid.UUID
	ItemID uuid.UUID
	Amount int32
}

func (q *Queries) AddItem(ctx context.Context, arg AddItemParams) (BagItem, error) {
	row := q.db.QueryRowContext(ctx, addItem, arg.BagID, arg.ItemID, arg.Amount)
	var i BagItem
	err := row.Scan(&i.BagID, &i.ItemID, &i.Amount)
	return i, err
}
