// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: item.sql

package database

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO Items (Id, ItemName)
VALUES ($1, $2)
RETURNING id, itemname
`

type CreateItemParams struct {
	ID       int32
	Itemname string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem, arg.ID, arg.Itemname)
	var i Item
	err := row.Scan(&i.ID, &i.Itemname)
	return i, err
}
