// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createUser = `-- name: CreateUser :one
INSERT INTO Users (Id, Name, SteamID)
VALUES ($1, $2, $3)
RETURNING id, name, steamid, bag
`

type CreateUserParams struct {
	ID      uuid.UUID
	Name    string
	Steamid string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Name, arg.Steamid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Steamid,
		pq.Array(&i.Bag),
	)
	return i, err
}

const getUserbyId = `-- name: GetUserbyId :one
SELECT id, name, steamid, bag
FROM Users
WHERE SteamID = $1
`

func (q *Queries) GetUserbyId(ctx context.Context, steamid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserbyId, steamid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Steamid,
		pq.Array(&i.Bag),
	)
	return i, err
}
