// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO Users (Id, Name, SteamID, Created_at, Updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, steamid, created_at, updated_at
`

type CreateUserParams struct {
	ID        uuid.UUID
	Name      string
	Steamid   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Steamid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Steamid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserbyId = `-- name: GetUserbyId :one
SELECT id, name, steamid, created_at, updated_at
FROM Users
WHERE SteamID = $1
`

func (q *Queries) GetUserbyId(ctx context.Context, steamid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserbyId, steamid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Steamid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
